<a href="https://colab.research.google.com/github/Vineesha2005/B-14_1873_PDS/blob/main/LAB-2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Student Grades Analysis Using NumPy

In [1]:
import numpy as np

# Step 1: Create a 2D NumPy array for student marks
# Assume 5 students and marks in 3 subjects
marks = np.array([
    [85, 78, 92],  # Student 1
    [76, 88, 69],  # Student 2
    [90, 82, 85],  # Student 3
    [65, 70, 72],  # Student 4
    [88, 95, 91]   # Student 5
])

print("Student Marks:\n", marks)

# Step 2: Calculate average, minimum, and maximum marks
avg_marks = np.mean(marks)
min_marks = np.min(marks)
max_marks = np.max(marks)

print("\nAverage Marks (Overall):", avg_marks)
print("Minimum Marks (Overall):", min_marks)
print("Maximum Marks (Overall):", max_marks)

# Step 3: Slicing to retrieve marks of specific students (e.g., 1st and 3rd student)
print("\nMarks of Student 1:", marks[0])
print("Marks of Student 3:", marks[2])

# Step 4: Boolean indexing → Find students scoring above 80 in any subject
students_above_80 = marks > 80
print("\nBoolean Array (True if marks > 80):\n", students_above_80)

# Step 5: Find students whose total marks > 240
total_marks = np.sum(marks, axis=1)
students_high_score = total_marks > 240
print("\nTotal Marks per Student:", total_marks)
print("Students with total marks > 240:", students_high_score)

# Step 6: Reshape array for subject-wise performance (Transpose)
subject_wise = marks.T
print("\nSubject-wise Performance:\n", subject_wise)

# Step 7: Comment based on results
print("\nAnalysis:")
print("→ Highest scorer has", np.max(total_marks), "marks.")
print("→ Average overall performance is", round(avg_marks, 2))
print("→ Best subject performance:", np.argmax(np.mean(subject_wise, axis=1)) + 1)


Student Marks:
 [[85 78 92]
 [76 88 69]
 [90 82 85]
 [65 70 72]
 [88 95 91]]

Average Marks (Overall): 81.73333333333333
Minimum Marks (Overall): 65
Maximum Marks (Overall): 95

Marks of Student 1: [85 78 92]
Marks of Student 3: [90 82 85]

Boolean Array (True if marks > 80):
 [[ True False  True]
 [False  True False]
 [ True  True  True]
 [False False False]
 [ True  True  True]]

Total Marks per Student: [255 233 257 207 274]
Students with total marks > 240: [ True False  True False  True]

Subject-wise Performance:
 [[85 76 90 65 88]
 [78 88 82 70 95]
 [92 69 85 72 91]]

Analysis:
→ Highest scorer has 274 marks.
→ Average overall performance is 81.73
→ Best subject performance: 2


Employee Salary Analysis with Pandas

In [2]:
import pandas as pd

# Step 1: Create a pandas DataFrame
data = {
    'Employee_ID': [101, 102, 103, 104, 105],
    'Name': ['Ravi', 'Priya', 'Kiran', 'Sneha', 'Arjun'],
    'Department': ['IT', 'HR', 'Finance', 'IT', 'Marketing'],
    'Salary': [55000, 45000, 65000, 52000, 70000]
}

df = pd.DataFrame(data)
print("Initial Employee Data:\n", df)

# Step 2: Filter employees with salary > 50,000
high_salary = df[df['Salary'] > 50000]
print("\nEmployees with Salary > 50,000:\n", high_salary)

# Step 3: Sort the DataFrame by salary in descending order
sorted_df = df.sort_values(by='Salary', ascending=False)
print("\nEmployees Sorted by Salary:\n", sorted_df)

# Step 4: Add a new column for Bonus (10% of Salary)
df['Bonus'] = df['Salary'] * 0.10
print("\nDataFrame with Bonus Column:\n", df)

# Step 5: Calculate total salary expense including bonuses
df['Total_Payout'] = df['Salary'] + df['Bonus']
total_expense = df['Total_Payout'].sum()
print("\nTotal Salary Expense (Including Bonus):", total_expense)

# Step 6: Save the DataFrame to a CSV file
df.to_csv("Employee_Salary_Analysis.csv", index=False)
print("\nCSV File 'Employee_Salary_Analysis.csv' Saved Successfully!")


Initial Employee Data:
    Employee_ID   Name Department  Salary
0          101   Ravi         IT   55000
1          102  Priya         HR   45000
2          103  Kiran    Finance   65000
3          104  Sneha         IT   52000
4          105  Arjun  Marketing   70000

Employees with Salary > 50,000:
    Employee_ID   Name Department  Salary
0          101   Ravi         IT   55000
2          103  Kiran    Finance   65000
3          104  Sneha         IT   52000
4          105  Arjun  Marketing   70000

Employees Sorted by Salary:
    Employee_ID   Name Department  Salary
4          105  Arjun  Marketing   70000
2          103  Kiran    Finance   65000
0          101   Ravi         IT   55000
3          104  Sneha         IT   52000
1          102  Priya         HR   45000

DataFrame with Bonus Column:
    Employee_ID   Name Department  Salary   Bonus
0          101   Ravi         IT   55000  5500.0
1          102  Priya         HR   45000  4500.0
2          103  Kiran    Finance   65